---
- hosts: localhost
  user: root
  gather_facts: no

#LVM Setup
  tasks:
   - name: vg_create
     lvg:
       vg: vgdata
       pvs: "/dev/oracleoci/oraclevdx"
   - name: lvcreate
     lvol:
       vg: vgdata
       lv: nfsdata
       size: 99%FREE
   - name: Create a ext4 filesystem on /dev/oracleoci/oraclevdx and check disk blocks
     filesystem:
       fstype: ext4
       dev: /dev/vgdata/nfsdata
   - name: Mount logical Volume
     mount:
        name: /nfsdata
        src: /dev/vgdata/nfsdata
        fstype: ext4
        state: mounted

#NFS setup
   - name: Ensure NFS utilities are installed.
     yum: name=nfs-utils state=installed

   - name: Ensure rpcbind is running.
     service: name=rpcbind state=started enabled=yes

   - name: copy /etc/exports
     template: src=exports.j2 dest=/etc/exports owner=root group=root mode=0644

   - name: restart nfs server
     service: name=nfs-server state=restarted

