- hosts: all
  become: true
  become_user: root
  vars: 
    create_lvsize: '100%FREE'
  tasks:
    - name: Create Volume Group on /dev/sdb
      lvg: vg=vg01 pvs=/dev/sdb
    
    - name: Create LV on VG01
      lvol: vg=vg01 lv=lv01 size={{ create_lvsize }}
     
    - name: Create et4 on vg01
      filesystem: fstype=ext4 dev=/dev/vg01/lv01 
    
    - name: Get blkid
      command: blkid -s UUID -o value /dev/mapper/vg01-lv01
      register: disk_blkid

    - name: mounting new filesystem
      mount: name=/u01 src='UUID={{ disk_blkid.stdout }}' fstype=ext4 state=mounted opts='defaults,noatime,_netdev' passno=2
      

