# ntp playbook - first attempt

- hosts: all
  user: opc
  become: yes
  become_user: root
  tasks:
  - iptables:
      chain: BareMetalInstanceServices
      rule_num: 8
      destination: 169.254.169.254/32
      destination_port: 123
      protocol: udp
      match: udp
      comment: Allow access to OCI local NTP service
      jump: ACCEPT
    
  - name: Install NTP
    yum: name=ntp state=installed 
    tags: ntp

  - name: Copy over the NTP configuration
    template: src=./templates/ntp.template.conf dest=/etc/ntp.conf
    notify:
    - restart ntpd
    tags: ntp
 
  - name: Make sure NTP is stopped
    service: name=ntpd state=stopped enabled=yes
    tags: ntp
 
  - name: Sync time initialy
    shell: ntpdate 169.254.169.254
    tags: ntp

  - name: Make sure NTP is started up
    service: name=ntpd state=started enabled=yes
    tags: ntp
