#
# Copyright (c) Oracle and/or its affiliates. All rights reserved.
#

title: CD3 Automation Toolkit WorkVM
description: CD3 Automation Toolkit WorkVM Deployment
informationalText: Welcome to CD3 Automation Toolkit WorkVM Deployment wizard
schemaVersion: 1.1.0
version: "20190719"
locale: "en"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: "put url for image if any"

# Used to group Outputs.  Any outputs not included in these defined groups, are
# included in a default group labelled "Outputs".
# (Optional) if not groups are given, outputs are not grouped at all.

variableGroups:
- title : CD3 Automation Toolkit WorkVM
  variables:
   - instance_compartment_strategy
   - parent_compartment_ocid
   - new_compartment_name
   - instance_compartment_ocid
   - instance_name
   - instance_os_version
   - instance_shape
   - instance_ocpus
   - instance_ram
   - boot_volume_size
   - instance_ad
   - instance_fd
   - ssh_public_key


- title : "Networking Details for CD3 Automation Toolkit WorkVM"
  variables:
  - vcn_strategy
  - vcn_compartment_ocid
  - existing_vcn_id
  - existing_subnet_id
  - assign_publicip_existing_subnet
  - assign_existing_nsg
  - existing_nsg_id
  - vcn_name
  - vcn_cidr
  - vcn_dns_label
  - subnet_name
  - subnet_cidr
  - subnet_dns_label
  - subnet_type
  - assign_public_ip
  - drg_attachment
  - existing_drg_id
  - source_cidr


- title: "Hidden Variables"
  visible: false
  variables:
  - subnet_id
  - nsg_id
  - tenancy_ocid
  - cloud_init_script
  - marketplace_source_images
  - mp_subscription_enabled
  - mp_listing_id
  - mp_listing_resource_id
  - mp_listing_resource_version
  - current_user_ocid
  - region

###########
# VARIABLES
###########
variables:
  instance_compartment_strategy:
    type: enum
    title: Select Compartment for CD3 Automation Toolkit Components
    description: Use existing or Create new Compartment. Stack must be provisioned in Home region if selecting new compartment
    enum:
    - "Use Existing Compartment"
    - "Create New Compartment - Stack must be provisioned in home region"
    required: true
    default: "Use Existing Compartment"
  instance_compartment_ocid:
    type: oci:identity:compartment:id
    title: Select CD3 Automation Toolkit WorkVM Compartment
    description: Compartment for CD3 Automation Toolkit WorkVM Components
    default: compartment_ocid
    visible:
      eq:
      - instance_compartment_strategy
      - "Use Existing Compartment"
    required: true
  parent_compartment_ocid:
    type: oci:identity:compartment:id
    title: Select Parent Compartment for New Compartment
    description: Parent Compartment of the new compartment to be created
    default: compartment_ocid
    visible:
      eq:
      - instance_compartment_strategy
      - "Create New Compartment - Stack must be provisioned in home region"
    required: true
  new_compartment_name:
    visible:
      eq:
      - instance_compartment_strategy
      - "Create New Compartment - Stack must be provisioned in home region"
    title: Enter New Compartment name for CD3 Automation Toolkit WorkVM components - VM, VCN etc
    description: New Compartment name for CD3 Automation Toolkit WorkVM components - VM, VCN etc
    type: string
    default: null
    required: true
  instance_name:
    visible:
    title: Enter display name/hostname for CD3 Automation Toolkit WorkVM
    description: CD3 Automation Toolkit WorkVM display name/hostname
    type: string
    default: "workvm"
    #pattern: "^([a-z][a-z0-9_-]{1,60})$"
    minLength: 1
    maxLength: 62
    required: true
  instance_os_version:
    visible:
    title: Select Instance Image
    description: Oracle Linux image OCID for VM provisioning
    type: enum
    enum:
    - "Oracle-Linux-7"
    - "Oracle-Linux-8"
    - "Oracle-Linux-9"
    default: "Oracle-Linux-9"
    #pattern: '^ocid1\.([a-z0-9_-]{1,32})\.([a-z0-9_-]{1,15})\.([a-z0-9]{0,24})\.([a-z0-9]{60})$'
    required: true
  instance_shape:
    type: enum
    title: Select Instance Shape
    description: Instance Shape
    enum:
    - "VM.Standard3.Flex"
    - "VM.Standard.E4.Flex"
    - "VM.Standard.E5.Flex"
    required: true
    default: "VM.Standard3.Flex"
  instance_ocpus:
    visible:
    type: integer
    title: Enter Instance OCPUs
    description: The total number of OCPUs assigned to the instance
    default: 2
    minimum: 1
    maximum: 64
    multipleOf: 1
    required: true
  instance_ram:
    visible:
    type: integer
    title: Enter Instance Memory In GBs
    description: The total amount of memory available to an instance (GB)
    default: 8
    minimum: 1
    maximum: 1024
    multipleOf: 1
    required: true
  boot_volume_size:
    visible:
    type: integer
    title: Boot volume size in GBs
    description: Boot volume size in GBs. Default is 50 GB and value should be multiple of 1.
    default: 50
    minimum: 50
    maximum: 32768
    multipleOf: 1
    required: true
  instance_ad:
    type: oci:identity:availabilitydomain:name
    title: Select Availability domain
    description: The Availability domain in which to create CD3 Automation Toolkit WorkVM
    dependsOn:
      compartmentId: ${instance_compartment_ocid}
    required: true
    visible: complexExpression

  instance_fd:
    type: oci:identity:faultdomain:name
    title: Select Fault domain
    description: The Fault domain in which to create CD3 Automation Toolkit WorkVM
    required: true
    dependsOn:
      compartmentId: ${instance_compartment_ocid}
      availabilityDomainName: ${instance_ad}
  ssh_public_key:
    visible:
    title: "Enter SSH Public Key"
    description: "Use the corresponding private key to access the CD3 Automation Toolkit WorkVM instance"
    type: oci:core:ssh:publickey
    required: true

  #Networking Details variables
  vcn_strategy:
    type: enum
    title: Network Details for CD3 Automation Toolkit WorkVM
    description: Use existing VCN or Create New VCN
    enum:
    - "Create New VCN"
    - "Use Existing VCN"
    required: true
    default: "Use Existing VCN"
  vcn_compartment_ocid:
    type: oci:identity:compartment:id
    title: Select Existing VCN's Compartment
    description: The existing compartment in which to create the VCN
    default: compartment_ocid
    visible:
        eq:
         - vcn_strategy
         - "Use Existing VCN"
    required: true
  existing_vcn_id:
    visible:
      eq:
      - vcn_strategy
      - "Use Existing VCN"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
    required: true
    title: Select Existing VCN
    description: An existing OCI VCN in which to create the CD3 Automation Toolkit WorkVM's network resources. Make sure the VCN has valid internet/NAT gateways
  existing_subnet_id:
    visible:
      eq:
      - vcn_strategy
      - "Use Existing VCN"
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${existing_vcn_id}
    required: true
    title: Select Existing Subnet
    description: An existing Subnet in which to create the CD3 Automation Toolkit WorkVM.
  assign_publicip_existing_subnet:
    visible:
      eq:
      - vcn_strategy
      - "Use Existing VCN"
    type: boolean
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${existing_vcn_id}
      subnetId:  ${existing_subnet_id}
    required: false
    title: If above selected subnet is Public, assign public IP to instance ?
    description: If above selected subnet is Public, assign public IP to instance ?
    default: false
  assign_existing_nsg:
    visible:
      eq:
      - vcn_strategy
      - "Use Existing VCN"
    type: boolean
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${existing_vcn_id}
    required: false
    title: Assign existing NSG to instance ?
    description: Assign existing NSG to instance ?
  existing_nsg_id:
    visible:
      eq:
      - assign_existing_nsg
      - true
    type: oci:core:nsg:id
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${existing_vcn_id}
    required: true
    title: Select existing NSG
    description: Select existing NSG to assign to WorkVM instance if any
    default: false
  vcn_name:
    visible:
      and:
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: string
    title: Enter VCN Name
    description: The name of the new OCI VCN to be created
    default: workvm-vcn
    required: true

  vcn_cidr:
    visible:
      eq:
      - vcn_strategy
      - "Create New VCN"
    type: string
    default: '172.16.0.0/24'
    title: Enter VCN CIDR
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: The CIDR to assign to the new virtual cloud network (VCN) to create for this service.  Example - 10.0.0.0/16
    required: true

  vcn_dns_label:
    visible:
      eq:
      - vcn_strategy
      - "Create New VCN"
    type: string
    default: 'workvm'
    title: Enter VCN DNS Label
    pattern: "^[a-zA-Z][a-zA-Z0-9]{0,14}$"
    description: The dns label for the VCN. Only letters and numbers, starting with a letter and can be a maximum of 15 characters..
    required: true

  subnet_name:
    visible:
      and:
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: string
    title: Enter Subnet Name
    description: The name of the new Subnet to create for this service.
    default: workvm-sub
    required: true

  subnet_cidr:
    visible:
      eq:
      - vcn_strategy
      - "Create New VCN"
    type: string
    default: '172.16.0.0/25'
    title: Enter Subnet CIDR
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: The CIDR to assign to the new Subnet. Example - 10.0.0.0/24
    required: true

  subnet_dns_label:
    visible:
      eq:
      - vcn_strategy
      - "Create New VCN"
    type: string
    default: 'workvmsub'
    title: Subnet DNS Label
    pattern: "^[a-zA-Z][a-zA-Z0-9]{0,14}$"
    description: The dns label for the Subnet. Only letters and numbers, starting with a letter and can be a maximum of 15 characters.
    required: true

  subnet_type:
    visible:
      and:
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: enum
    title: Select Subnet Type
    description: Type of Subnet to create. Private or Public.
    enum:
     - "Private"
     - "Public"
    default: Private
    required: true

  assign_public_ip:
    visible:
      and:
        - eq:
          - subnet_type
          - "Public"
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: boolean
    title: Assign Public IP to Instance ?
    description: Assign Public IP to Instance ?
    default: false
    required: false

  drg_attachment:
    visible:
      and:
        - eq:
          - vcn_strategy
          - "Create New VCN"
    type: boolean
    title: Attach new VCN to already existing DRG ?
    description: Attach new VCN to already existing DRG ?
    default: false
    required: false
  existing_drg_id:
    visible:
      and:
       - eq:
         - vcn_strategy
         - "Create New VCN"
       - eq:
         - drg_attachment
         - true
    type: string
    pattern: '^ocid1\.([a-z0-9_-]{1,32})\.([a-z0-9_-]{1,15})\.([a-z0-9_-]{0,24})\.([a-z0-9]{60})$'
    required: true
    title: Enter Existing DRG OCID
    description: Enter existing DRG OCID

  source_cidr:
    visible:
      eq:
      - vcn_strategy
      - "Create New VCN"
    type: array
    items:
      type: string
    #  pattern: "^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
    minItems: 1
    uniqueItems: true
    default: []
    title: Enter Source IP/CIDR from where CD3 Automation Toolkit WorkVM will be accessed. (Rule will be created in NSG to allow ssh on port 22 and jenkins on port 8443)
    description: Example - 10.0.0.0/24. If left empty, security rules need to be added later to allow required access.
    required: false

  subnet_id:
    type: string
  nsg_id:
    type: string
  cloud_init_script:
    type: string
  marketplace_source_images:
    type: map
  mp_subscription_enabled:
    type: bool
  mp_listing_id:
    type: string
  mp_listing_resource_id:
    type: string
  mp_listing_resource_version:
    type: string
  tenancy_ocid:
    type: string