[Default]

##################################################################################################################
                            ## Required Parameters ##
##################################################################################################################

# Friendly name for the AWS account environment
# Generated terraform files will be prefixed with this
prefix=

##################################################################################################################
                            ## Auth Details Parameters ##
##################################################################################################################

# AWS Access Key
aws_access_key_id=

# AWS Secret Key
aws_secret_access_key=


