[Default]

##################################################################################################################
                            ## Required Parameters ##
##################################################################################################################

# Friendly name for the Customer; The generated .auto.tfvars files will be prefixed with this
prefix=

# Auth Mechanism for GCP APIs - api_key
# Please make sure to add IAM policies for service account before executing connectContainerToGCP.py
auth_mechanism=api_key
# Path to JSON file having private key information for the service account;
# Defaults to /cd3user/gcp/keys/gcp_api_private.json when left empty
config_file=

