[Default]

#Input variables required to run setUpGCP script

#path to output directory where terraform files will be generated. eg. /cd3user/gcp/<prefix>/terraform_files
outdir=

#prefix for output terraform files eg demo
prefix=

# Auth Params
# auth mechanism for GCP APIs - api_key
auth_mechanism=api_key

#input credentials file for service account eg /cd3user/gcp/<prefix>/gcp_api_private.json
config_file=

#path to cd3 excel eg /cd3user/gcp/<prefix>/CD3-Customer.xlsx
cd3file=

#specify create_resources to create new resources in GCP(greenfield workflow)
#specify export_resources to export resources from GCP(non-greenfield workflow)
workflow_type=create_resources