- hosts: all
  become: true
  become_user: root
  vars_files:
    - variables.yml
  tasks:
    - name: Create Volume Group on /dev/sdb
      lvg: vg=vg01 pvs={{ volume.pvs }}

    - name: Create LV on VG01
      lvol: vg=vg01 lv=lv01 size={{ volume.create_lvsize }}

    - name: Create ext4 on vg01
      filesystem: fstype=ext4 dev=/dev/vg01/lv01

    - name: Get blkid
      command: blkid -s UUID -o value /dev/mapper/vg01-lv01
      register: disk_blkid

    - name: mounting new filesystem on /images
      mount: name=/images src='UUID={{ disk_blkid.stdout }}' fstype=ext4 state=mounted opts='defaults,noatime,_netdev' passno=2

    - name: Create /images/migration_logs
      file:
        path: /images/migration_logs
        state: directory
        owner: opc
        group: opc
        mode: 0755

    - name: Create /images/processed
      file:
        path: /images/processed
        state: directory
        owner: opc
        group: opc
        mode: 0755
