#!/bin/bash
 while true
 do
    if [ -e /home/opc/shell_script*.sh ]
    then
        echo "file exists"
        break
    fi
done
cd /home/opc
sleep 5
chmod +x shell_script*.sh
yum -y install dos2unix
dos2unix shell_script*.sh shell_script*.sh
./shell_script.sh