# Generated by Django 3.1.2 on 2020-12-04 14:33

from django.db import migrations, models
import django.utils.timezone
import vcn.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stack_Name', models.CharField(max_length=256, unique=True, verbose_name='Customer Name')),
                ('Username', models.CharField(max_length=256)),
                ('Tenancy_OCID', models.CharField(max_length=256)),
                ('Fingerprint', models.CharField(max_length=256)),
                ('User_OCID', models.CharField(max_length=256)),
                ('Region', models.CharField(choices=[('us-ashburn-1', 'us-ashburn-1'), ('us-phoenix-1', 'us-phoenix-1'), ('uk-london-1', 'uk-london-1'), ('eu-frankfurt-1', 'eu-frankfurt-1'), ('ca-toronto-1', 'ca-toronto-1'), ('ap-tokyo-1', 'ap-tokyo-1'), ('ap-seoul-1', 'ap-seoul-1'), ('ap-mumbai-1', 'ap-mumbai-1'), ('ap-sydney-1', 'ap-sydney-1'), ('sa-saopaulo-1', 'sa-saopaulo-1'), ('eu-zurich-1', 'eu-zurich-1')], default=None, max_length=256)),
                ('CD3_Excel', models.FileField(upload_to=vcn.models.file_upload_path_excel, verbose_name='CD3 Excel(xlsx/xls format)')),
                ('Key_File', models.FileField(upload_to='', verbose_name='Key File (.pem)')),
                ('Compartment', models.BooleanField(default=False, verbose_name='Compartments')),
                ('Groups', models.BooleanField(default=False, verbose_name='Groups,Policies')),
                ('Network', models.CharField(choices=[('Create Network', 'Create Network'), ('Modify Network ', 'Modify Network'), ('Export Security Rule& Route Rules', 'Export Security Rule& Route Rules'), ('Modify Security Rules & Route Rules', 'Modify Security Rules & Route Rules')], default=None, max_length=256)),
                ('NSG', models.BooleanField(default=False, verbose_name='Network Security Groups')),
                ('Instance', models.BooleanField(default=False, verbose_name='Instances')),
                ('Block_Volume', models.BooleanField(default=False, verbose_name='Block Volumes')),
                ('RM', models.BooleanField(default=False, verbose_name='Resource Manager(Plan Only)')),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Stack_Update', models.BooleanField(default=False)),
                ('Terraform_Files', models.CharField(max_length=256)),
                ('Compartment_Name', models.CharField(max_length=256, verbose_name='Resource Manager Compartment Name')),
            ],
        ),
    ]
