# Generated by Django 3.1.4 on 2020-12-06 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='Export_Compartment_Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Network',
            field=models.CharField(choices=[('Create Network', 'Create Network'), ('Modify Network ', 'Modify Network'), ('Export Security Rule& Route Rules', 'Export Security Rule & Route Rules'), ('Modify Security Rules & Route Rules', 'Modify Security Rules & Route Rules')], default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Region',
            field=models.CharField(choices=[('', 'select'), ('us-ashburn-1', 'us-ashburn-1'), ('us-phoenix-1', 'us-phoenix-1'), ('uk-london-1', 'uk-london-1'), ('eu-frankfurt-1', 'eu-frankfurt-1'), ('ca-toronto-1', 'ca-toronto-1'), ('ap-tokyo-1', 'ap-tokyo-1'), ('ap-seoul-1', 'ap-seoul-1'), ('ap-mumbai-1', 'ap-mumbai-1'), ('ap-sydney-1', 'ap-sydney-1'), ('sa-saopaulo-1', 'sa-saopaulo-1'), ('eu-zurich-1', 'eu-zurich-1')], max_length=256),
        ),
    ]
