# Generated by Django 3.1.4 on 2020-12-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0002_auto_20201206_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Export_Compartment_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Network',
            field=models.CharField(choices=[('Create Network', 'Create Network'), ('Modify Network ', 'Modify Network'), ('Modify Security Rules & Route Rules', 'Modify Security Rules & Route Rules'), ('Export Security Rule& Route Rules', 'Export Security Rule & Route Rules')], default=None, max_length=256),
        ),
    ]
