# Generated by Django 3.1.4 on 2020-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0003_auto_20201206_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Compartment_Name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Resource Manager Compartment Name'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Network',
            field=models.CharField(blank=True, choices=[('Create Network', 'Create Network'), ('Modify Network ', 'Modify Network'), ('Modify Security Rules & Route Rules', 'Modify Security Rules & Route Rules'), ('Export Security Rule& Route Rules', 'Export Security Rule & Route Rules')], default=None, max_length=256, null=True),
        ),
    ]
