# Generated by Django 3.1.4 on 2020-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0004_auto_20201206_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Network',
            field=models.CharField(choices=[('Create Network', 'Create Network'), ('Modify Network ', 'Modify Network'), ('Modify Security Rules & Route Rules', 'Modify Security Rules & Route Rules'), ('Export Security Rule& Route Rules', 'Export Security Rule & Route Rules')], default=None, max_length=256),
        ),
    ]
