# Generated by Django 3.1.2 on 2020-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0007_auto_20201206_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Network',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
