# Generated by Django 3.1.2 on 2020-12-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0008_auto_20201207_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Network',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
