# Generated by Django 3.1.2 on 2020-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0009_auto_20201207_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='Instance_SSH_Public_Key',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
