# Generated by Django 3.1.2 on 2020-12-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0010_tenancy_instance_ssh_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Instance_SSH_Public_Key',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
