# Generated by Django 3.1.2 on 2020-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0011_auto_20201208_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='Instance_SSH_Public_Value',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Instance_SSH_Public_Key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
