# Generated by Django 3.1.2 on 2020-12-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0012_auto_20201208_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='Stack_OCID',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
