# Generated by Django 3.1.2 on 2020-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0013_tenancy_stack_ocid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Instance_SSH_Public_Key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Instance_SSH_Public_Value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Stack_Name',
            field=models.CharField(max_length=256, verbose_name='Customer Name'),
        ),
        migrations.AlterUniqueTogether(
            name='tenancy',
            unique_together={('Stack_Name', 'Username')},
        ),
    ]
