# Generated by Django 3.1.2 on 2020-12-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0014_auto_20201211_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenancy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(fields=('Stack_Name', 'Username'), name='Customer name already exist'),
        ),
    ]
