# Generated by Django 3.1.2 on 2020-12-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0015_auto_20201211_1548'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='Customer name already exist',
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='Stack_Name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Customer Name'),
        ),
        migrations.AlterUniqueTogether(
            name='tenancy',
            unique_together={('Stack_Name', 'Username')},
        ),
    ]
