# Generated by Django 3.1.2 on 2020-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcn', '0016_auto_20201211_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='Stack_Name',
            field=models.CharField(max_length=256, verbose_name='Customer Name'),
        ),
        migrations.AlterUniqueTogether(
            name='tenancy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(fields=('Stack_Name', 'Username'), name='Customer already exist'),
        ),
    ]
