name: SonarQube Scan
on:
  push:
    branches: [ "develop-old" ]
  pull_request:
    branches: [ "develop-old" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # ref: ${{ github.event.pull_request.head.ref }}
          # repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
      
      - name: Install Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-*.zip
          echo "$PWD/sonar-scanner-*/bin" >> $GITHUB_PATH

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=cd3-automation-toolkit \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
